default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello-rails-back-end
  username: sebastianhm
  password: sehemu
  host: localhost
  port: 5432

test:
  <<: *default
  database: hello-rails-back-end_test
  username: sebastianhm
  password: sehemu

production:
  <<: *default
  database: hello-rails-back-end_production
  username: hello-rails-back-end
  password: <%= ENV["HELLO-RAILS-BACK-END_DATABASE_PASSWORD"] %>